export interface CampusPerson {
  name: string;
  role: string;
  detail: string;
  login?: string;
}

/** Campus staff from Win.gg / Gaming Amigos / Kai’s Class of 2026 reveal. */
export const suStaff: CampusPerson[] = [
  { name: "Kai Cenat", role: "Dean", detail: "Dean of Streamer University", login: "kaicenat" },
  { name: "Fanum", role: "SU Police · Lead", detail: "Campus police department", login: "fanum" },
  { name: "Walton", role: "SU Police · Officer", detail: "Campus security / police" },
  { name: "Devonte Cenat", role: "Janitor", detail: "Janitor department", login: "devontecenat" },
  { name: "Kelo", role: "Janitor", detail: "Former student · janitor department" },
  { name: "ChrisNxtDoor", role: "Janitor", detail: "Janitor department", login: "chrisnxtdoor" },
  { name: "iJustLovePuzzles", role: "Librarian", detail: "Campus librarian · puzzle station", login: "ijustlovepuzzles" },
  { name: "YourRAGE", role: "Guidance Counselor", detail: "Campus guidance", login: "yourragegaming" },
];

/**
 * Full Class of 2026 student roster from Sportskeeda / Gaming Amigos / K24 coverage.
 * Logins are best-effort Twitch handles for live Helix lookups.
 */
export const suStudents: CampusPerson[] = [
  { name: "McqueenLive", role: "Student", detail: "Golden Ticket · Mafiathon 3", login: "mcqueenlive" },
  { name: "Aikooofficial", role: "Student", detail: "Class of 2026", login: "aikooofficial" },
  { name: "Smokecertified", role: "Student", detail: "Class of 2026", login: "smokecertified" },
  { name: "straight2thbank__", role: "Student", detail: "Class of 2026", login: "straight2thbank__" },
  { name: "coolbutterflyyyy", role: "Student", detail: "Class of 2026", login: "coolbutterflyyyy" },
  { name: "Thatsdaveontv", role: "Student", detail: "Class of 2026", login: "thatsdaveontv" },
  { name: "IWasTori", role: "Student", detail: "Class of 2026", login: "iwastori" },
  { name: "OfficeDrummer", role: "Student", detail: "Class of 2026", login: "officedrummer" },
  { name: "MeesterKeem", role: "Student", detail: "Class of 2026", login: "meesterkeem" },
  { name: "Juicy Jacob", role: "Student", detail: "Class of 2026", login: "juicyjacob" },
  { name: "TheRealMiyaLive", role: "Student", detail: "Class of 2026", login: "therealmiyalive" },
  { name: "Queen Naija", role: "Student", detail: "Class of 2026", login: "queennaija" },
  { name: "Kiara Sainte", role: "Student", detail: "Class of 2026", login: "kiarasainte" },
  { name: "Fvkingjosh", role: "Student", detail: "Class of 2026", login: "fvkingjosh" },
  { name: "Tiana Musarra", role: "Student", detail: "Class of 2026", login: "tianamusarra" },
  { name: "Mookie", role: "Student", detail: "Class of 2026", login: "mookie" },
  { name: "Skai Jackson", role: "Student", detail: "Class of 2026", login: "skaijackson" },
  { name: "SukiMellow", role: "Student", detail: "Class of 2026", login: "sukimellow" },
  { name: "Benjychavez", role: "Student", detail: "Class of 2026", login: "benjychavez" },
  { name: "Sketch", role: "Student", detail: "Gifted Kai a chain on Day 1", login: "sketch" },
  { name: "MyaNicoleLive", role: "Student", detail: "Class of 2026", login: "myanicolelive" },
  { name: "rizzy_streamz", role: "Student", detail: "Class of 2026", login: "rizzy_streamz" },
  { name: "RunikTV", role: "Student", detail: "Class of 2026", login: "runiktv" },
  { name: "ilikehaskell", role: "Student", detail: "Class of 2026", login: "ilikehaskell" },
  { name: "Avazura", role: "Student", detail: "Class of 2026", login: "avazura" },
  { name: "TheMightyBA", role: "Student", detail: "Class of 2026", login: "themightyba" },
  { name: "Jordyn Lucas", role: "Student", detail: "Class of 2026", login: "jordynlucas" },
  { name: "Damii", role: "Student", detail: "Class of 2026", login: "damii" },
  { name: "AngelCrackedU", role: "Student", detail: "Class of 2026", login: "angelcrackedu" },
  { name: "TaylorJasminee", role: "Student", detail: "Class of 2026", login: "taylorjasminee" },
  { name: "Real_BigAnt", role: "Student", detail: "Class of 2026", login: "real_bigant" },
  { name: "Silky", role: "Student", detail: "Class of 2026", login: "silky" },
  { name: "Xscapeverse", role: "Student", detail: "Class of 2026", login: "xscapeverse" },
  { name: "Yusuf7n", role: "Student", detail: "Class of 2026", login: "yusuf7n" },
  { name: "ElinaMeng", role: "Student", detail: "Class of 2026", login: "elinameng" },
  { name: "StanleyyMeng", role: "Student", detail: "Class of 2026", login: "stanleyymeng" },
  { name: "ImDavisss", role: "Student", detail: "Class of 2026", login: "imdavisss" },
  { name: "Marlea", role: "Student", detail: "Class of 2026", login: "marlea" },
  { name: "AmberrTyson", role: "Student", detail: "Class of 2026", login: "amberrtyson" },
  { name: "EdwardkSo", role: "Student", detail: "Class of 2026", login: "edwardkso" },
  { name: "Clarencenyc", role: "Student", detail: "Class of 2026", login: "clarencenyc" },
  { name: "Aishah Sofey", role: "Student", detail: "Class of 2026", login: "aishahsofey" },
  { name: "Andrejmihelson", role: "Student", detail: "Class of 2026", login: "andrejmihelson" },
  { name: "2xceeej", role: "Student", detail: "Class of 2026", login: "2xceeej" },
  { name: "LailaSimmoneTV", role: "Student", detail: "Class of 2026", login: "lailasimonnetv" },
  { name: "Ft.Gioo", role: "Student", detail: "Class of 2026", login: "ftgioo" },
  { name: "Bonnie", role: "Student", detail: "Class of 2026", login: "bonnie" },
  { name: "Tatum Bittick", role: "Student", detail: "Class of 2026", login: "tatumbittick" },
  { name: "Marlon", role: "Student", detail: "Class of 2026", login: "marlon" },
  { name: "iwantacinnamonroll", role: "Student", detail: "Class of 2026", login: "iwantacinnamonroll" },
  { name: "TheyCallMeLeii", role: "Student", detail: "Class of 2026", login: "theycallmeleii" },
  { name: "JadaMalayTV", role: "Student", detail: "Class of 2026", login: "jadamalaytv" },
  { name: "shazdelicious", role: "Student", detail: "Class of 2026", login: "shazdelicious" },
  { name: "JayMommy0", role: "Student", detail: "Class of 2026", login: "jaymommy0" },
  { name: "Suhmmiee", role: "Student", detail: "Class of 2026", login: "suhmmiee" },
  { name: "NotBilzo", role: "Student", detail: "Class of 2026", login: "notbilzo" },
  { name: "Keirapleaze", role: "Student", detail: "Class of 2026", login: "keirapleaze" },
  { name: "Stable Ronaldo", role: "Student", detail: "Class of 2026", login: "stableronaldo" },
  { name: "Rawdogmoon", role: "Student", detail: "Class of 2026", login: "rawdogmoon" },
  { name: "RaphaelSoloLive", role: "Student", detail: "Class of 2026", login: "raphaelsololive" },
  { name: "LuhLiv1", role: "Student", detail: "Class of 2026", login: "luhliv1" },
  { name: "NotQuiteLikeDuB", role: "Student", detail: "Class of 2026", login: "notquitelikedub" },
  { name: "Catrnado", role: "Student", detail: "Class of 2026", login: "catrnado" },
  { name: "dcthedesigner", role: "Student", detail: "Class of 2026", login: "dcthedesigner" },
  { name: "Rizpy", role: "Student", detail: "Class of 2026", login: "rizpy" },
  { name: "PlaqueBoyMax", role: "Student", detail: "Class of 2026", login: "plaqueboymax" },
  { name: "Pudgieee", role: "Student", detail: "Class of 2026", login: "pudgieee" },
  { name: "Fumibean", role: "Student", detail: "Class of 2026", login: "fumibean" },
  { name: "WardrobeWinter", role: "Student", detail: "Class of 2026", login: "wardrobewinter" },
  { name: "WrldKailee", role: "Student", detail: "Class of 2026", login: "wrldkailee" },
  { name: "Sara Saffari", role: "Student", detail: "Class of 2026", login: "sarasaffari" },
  { name: "Coolitshawty", role: "Student", detail: "Class of 2026", login: "coolitshawty" },
  { name: "Flako", role: "Student", detail: "Class of 2026", login: "flako" },
  { name: "Carterefe", role: "Student", detail: "First international student", login: "carterefe" },
  { name: "A2guapo", role: "Student", detail: "Class of 2026", login: "a2guapo" },
  { name: "chris_gone_crazy", role: "Student", detail: "Class of 2026", login: "chris_gone_crazy" },
  { name: "kiingjojo", role: "Student", detail: "Class of 2026", login: "kiingjojo" },
  { name: "JasonTheWeen", role: "Student", detail: "Class of 2026", login: "jasontheween" },
  { name: "BlazinBeautyAlexis", role: "Student", detail: "Class of 2026", login: "blazinbeautyalexis" },
  { name: "YnlGeo", role: "Student", detail: "Class of 2026", login: "ynlgeo" },
  { name: "Madi2hotty", role: "Student", detail: "Class of 2026", login: "madi2hotty" },
  { name: "Crystalizaguirre", role: "Student", detail: "Class of 2026", login: "crystalizaguirre" },
  { name: "Malek_04", role: "Student", detail: "Class of 2026", login: "malek_04" },
  { name: "Yugi2x", role: "Student", detail: "Class of 2026", login: "yugi2x" },
  { name: "Seleolu", role: "Student", detail: "Class of 2026", login: "seleolu" },
  { name: "King68thegreat", role: "Student", detail: "Class of 2026", login: "king68thegreat" },
  { name: "CuteGunz", role: "Student", detail: "Class of 2026", login: "cutegunz" },
  { name: "Therealnialove", role: "Student", detail: "Class of 2026", login: "therealnialove" },
  { name: "Dreamdoll", role: "Student", detail: "Class of 2026", login: "dreamdoll" },
  { name: "MandoMillions", role: "Student", detail: "Class of 2026", login: "mandomillions" },
  { name: "Lanializa", role: "Student", detail: "Class of 2026", login: "lanializa" },
  { name: "Jshock9nine", role: "Student", detail: "Class of 2026", login: "jshock9nine" },
  { name: "Lacy", role: "Student", detail: "Class of 2026", login: "lacy" },
  { name: "SarahFarrugia", role: "Student", detail: "Class of 2026", login: "sarahfarrugia" },
  { name: "Regtoofunny", role: "Student", detail: "Class of 2026", login: "regtoofunny" },
  { name: "SoPink", role: "Student", detail: "Class of 2026", login: "sopink" },
  { name: "Shonyx", role: "Student", detail: "Class of 2026", login: "shonyx" },
  { name: "AndrewUhrik", role: "Student", detail: "Class of 2026", login: "andrewuhrik" },
  { name: "Ezee", role: "Student", detail: "Class of 2026", login: "ezee" },
  { name: "Rulaempire_", role: "Student", detail: "Class of 2026", login: "rulaempire_" },
  { name: "Sierrasprague", role: "Student", detail: "Class of 2026", login: "sierrasprague" },
  { name: "Bonita", role: "Student", detail: "Class of 2026", login: "bonita" },
  { name: "Reemknocks", role: "Student", detail: "Class of 2026", login: "reemknocks" },
  { name: "MadaiChakell", role: "Student", detail: "Class of 2026", login: "madaichakell" },
  { name: "Aozami", role: "Student", detail: "Class of 2026", login: "aozami" },
  { name: "Braeden", role: "Student", detail: "Class of 2026", login: "braeden" },
  { name: "E11ysa", role: "Student", detail: "Class of 2026", login: "e11ysa" },
  { name: "FindJeremiah", role: "Student", detail: "Class of 2026", login: "findjeremiah" },
  { name: "Ysabella Grace", role: "Student", detail: "Class of 2026", login: "ysabellagrace" },
  { name: "Kanel Joseph", role: "Student", detail: "Private jet Day 1 moment", login: "kaneljoseph" },
  { name: "Blazian", role: "Student", detail: "Class of 2026", login: "blazian" },
  { name: "JaidaBunni", role: "Student", detail: "Class of 2026", login: "jaidabunni" },
  { name: "Noemi", role: "Student", detail: "Class of 2026", login: "noemi" },
  { name: "Dopeboyoli", role: "Student", detail: "Class of 2026", login: "dopeboyoli" },
  { name: "Chakra Shooter", role: "Student", detail: "Class of 2026", login: "chakrashooter" },
  { name: "OnlyLarryKing", role: "Student", detail: "1arryk", login: "1arryk" },
  { name: "Yaboyywill", role: "Student", detail: "Class of 2026", login: "yaboyywill" },
  { name: "PayBae", role: "Student", detail: "Class of 2026", login: "paybae" },
  { name: "WabeWrld", role: "Student", detail: "Class of 2026", login: "wabewrld" },
  { name: "Suburb Baby", role: "Student", detail: "Class of 2026", login: "suburbbaby" },
];

export function getStudentLogins() {
  return suStudents.map((student) => student.login).filter((login): login is string => Boolean(login));
}

export function getCampusPeople(): CampusPerson[] {
  return [...suStaff, ...suStudents];
}
